name: Release

on:
  push:
    branches:
      - next
      - next-major
      - beta
      - alpha

  workflow_dispatch:

jobs:
  semantic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN_RELEASE: ${{ secrets.GH_TOKEN_RELEASE }}
        with:
          semantic_version: 17.4.2
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            ${{ github.workspace }}

      - name: New release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: echo ${{ steps.semantic.outputs.new_release_version }}
